SELECT DESTINO , COUNT(DESTINO) AS QTD_DESTINO FROM PASSAGEM 
GROUP BY DESTINO
HAVING QTD_DESTINO > 1;

SELECT DESTINO , AVG(VALOR) FROM PASSAGEM 
GROUP BY DESTINO
ORDER BY AVG(VALOR) DESC;

SELECT NOME_COMPANHIA_AEREA , COUNT(FK_COMPANHIA_AEREA) FROM COMPANHIA_AEREA
JOIN FUNCIONARIOS
ON ID_COMPANHIA_AEREA = FK_COMPANHIA_AEREA
GROUP BY NOME_COMPANHIA_AEREA;

SELECT COUT(NOME_FUNCIONARIO) FROM FUNCIONARIOS;

