CREATE DATABASE UFC;

USE UFC;

CREATE TABLE PASSAGEIRO(
	ID_PASSAGEIRO INT PRIMARY KEY auto_increment , 
    NOME_PASSAGEIRO VARCHAR(50) NOT NULL , 
    CPF char(11) NOT NULL UNIQUE , 
    DATA_NASCIMENTO DATE NOT NULL , 
    NATURALIDADE VARCHAR(30) NOT NULL ,
    IDADE INT NOT NULL
);

CREATE TABLE BAGAGEM (
	ID_BAGAGEM INT PRIMARY KEY auto_increment , 
    TIPO VARCHAR(40) NOT NULL , 
    PESO DECIMAL NOT NULL , 
    FK_ID_PASSAGEIRO INT , 
    FOREIGN KEY (FK_ID_PASSAGEIRO) REFERENCES PASSAGEIRO (ID_PASSAGEIRO)
);

CREATE TABLE COMPANHIA_AEREA(
	ID_COMPANHIA_AEREA INT PRIMARY KEY auto_increment , 
    NOME_COMPANHIA_AEREA varchar(30) NOT NULL UNIQUE , 
    STATUS_COMPANHIA_AEREA boolean NOT NULL
);

CREATE TABLE AERONAVE (
	ID_AERONAVE INT PRIMARY KEY auto_increment , 
    CODIGO_IDENTIFICACAO VARCHAR(10) NOT NULL UNIQUE , 
    FK_COMPANHIA_AEREA INT , 
    FOREIGN KEY (FK_COMPANHIA_AEREA) REFERENCES COMPANHIA_AEREA (ID_COMPANHIA_AEREA)
);

CREATE TABLE FUNCIONARIOS(
	ID_FUNCIONARIOS INT PRIMARY KEY auto_increment , 
    NOME_FUNCIONARIO VARCHAR(50) NOT NULL , 
    DATA_NASCIMENTO DATE NOT NULL , 
    CPF CHAR(11) NOT NULL UNIQUE , 
    FK_COMPANHIA_AEREA INT , 
    FOREIGN KEY (FK_COMPANHIA_AEREA) REFERENCES COMPANHIA_AEREA (ID_COMPANHIA_AEREA)
);

CREATE TABLE PORTAO_TERMINAL (
	ID_PORTAO_TERMINAL INT PRIMARY KEY auto_increment , 
    NUMERO_PORTAO INT , 
    TIPO ENUM('NACIONAL' , 'INTERNACIONAL')
);

CREATE TABLE VOO (
	ID_VOO INT PRIMARY KEY auto_increment , 
    CODIGO_VOO VARCHAR(30) NOT NULL UNIQUE , 
    HORARIO_PARTIDA DATETIME NOT NULL, 
    HORARIO_CHEGADA DATETIME NOT NULL,
    OBSERVACAO ENUM('ATRASADO' , 'CONFIRMADO' , 'CANCELADO') , 
    FK_PORTAO_TERMINAL INT , 
    FK_COMPANHIA_AEREA INT ,
    FOREIGN KEY (FK_PORTAO_TERMINAL) REFERENCES PORTAO_TERMINAL (ID_PORTAO_TERMINAL) , 
    FOREIGN KEY (FK_COMPANHIA_AEREA) REFERENCES COMPANHIA_AEREA (ID_COMPANHIA_AEREA)
);

CREATE TABLE ESCALA_FUNCIONARIOS (
    ID_ESCALA INT PRIMARY KEY auto_increment , 
    FK_FUNCIONARIOS INT , 
    FK_AERONAVE INT , 
    DIA_TRABALHO DATETIME , 
    FOREIGN KEY (FK_FUNCIONARIOS) REFERENCES FUNCIONARIOS (ID_FUNCIONARIOS) , 
    FOREIGN KEY (FK_AERONAVE) REFERENCES AERONAVE (ID_AERONAVE)
);

CREATE TABLE PASSAGEM (
	ID_PASSAGEM INT primary KEY auto_increment , 
    FK_VOO INT , 
    FK_PASSAGEIRO INT , 
    VALOR DECIMAL , 
    CLASSE ENUM('EXECUTIVA' , 'ECONOMICA') ,
    DESTINO VARCHAR(30) NOT NULL ,
    FOREIGN KEY (FK_VOO) REFERENCES VOO (ID_VOO), 
    FOREIGN KEY (FK_PASSAGEIRO) REFERENCES PASSAGEIRO (ID_PASSAGEIRO)
);